GET http://localhost:8000/api/goals


###
POST http://localhost:8000/api/goals
Content-Type: application/json

{
  "text": "My second goal"
}


###
PUT http://localhost:8000/api/goals/6244c5507bfccc27f1b0f54d
Content-Type: application/json

{
  "text": "My updated goal"
}


###
DELETE http://localhost:8000/api/goals/6244c5507bfccc27f1b0f54d